basePath: /api/v1
definitions:
  handlers.PingAPIResponse:
    properties:
      golangRuntime:
        type: string
      pong:
        type: string
      version:
        type: string
    type: object
host: vulscano.vsnl.co.in:443
info:
  contact:
    email: sebastien.pouplin@tatacommunications.com
    name: Vulscano API Support
    url: https://github.com/lucabrasi83/vulscano/issues
  description: Swagger API documentation for TATA Communications Vulscano.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Vulscano API Documentation
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Verify the API is responding to HTTP requests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingAPIResponse'
            type: object
      summary: Ping Health Check
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
