run:    
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
linters:
  enable:
    - golint
    - gosimple
    - gocritic
    - stylecheck
    - gofmt
  fast: false
service:
  project-path: github.com/lucabrasi83/vscan
  golangci-lint-version: 1.16.0 # use fixed version to not introduce new linters unexpectedly

  
