run:    
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
# enable linters below
linters:
  enable:
    - golint
    - gosimple
    - gocritic
    - stylecheck
    - gofmt
  fast: false
service:
  project-path: github.com/lucabrasi83/vulscano
  golangci-lint-version: 1.13.1 # use fixed version to not introduce new linters unexpectedly

  
