language: go

env:
  global:
      - GO111MODULE=on
      - CODECOV_TOKEN="591bd614-fea0-4dd5-b816-6cbd5db6a834"

go:
  - 1.12.x

install: true

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 
    go build -a -ldflags="-X github.com/lucabrasi83/vulscano/initializer.Commit=$(git rev-parse --short HEAD) 
    -X github.com/lucabrasi83/vulscano/initializer.Version=$(git describe --tags) 
    -X github.com/lucabrasi83/vulscano/initializer.BuiltAt=$(date +%FT%T%z) 
    -X github.com/lucabrasi83/vulscano/initializer.BuiltOn=$(hostname)" -o vulscano

  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
