services:
  - redis-server

language: go

env:
  global:
      - GO111MODULE=on
      - CODECOV_TOKEN="591bd614-fea0-4dd5-b816-6cbd5db6a834"
      - VSCAN_REDIS_HOST=localhost
      - VSCAN_REDIS_PASSWORD=

go:

  - 1.13.x


install: true

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 
    go build -a -ldflags="-X github.com/lucabrasi83/vscan/initializer.Commit=$(git rev-parse --short HEAD)
    -X github.com/lucabrasi83/vscan/initializer.Version=$(git describe --tags)
    -X github.com/lucabrasi83/vscan/initializer.BuiltAt=$(date +%FT%T%z)
    -X github.com/lucabrasi83/vscan/initializer.BuiltOn=$(hostname)" -o vscan

  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
