---
version: "3.2"

services:
    # Vulscano API Core
    vulscano-core:
       image: tatacomm/vulscano:latest
       restart: always
       stdin_open: true
       tty: true
       hostname: vulscano-core
       depends_on:
            - vulscano-db
       environment:
            - VULSCANO_OPENVULN_CLIENT_ID=${VULSCANO_OPENVULN_CLIENT_ID}
            - VULSCANO_OPENVULN_CLIENT_SECRET=${VULSCANO_OPENVULN_CLIENT_SECRET}
            - VULSCANO_CISCO_ROUTER_USERNAME=${VULSCANO_CISCO_ROUTER_USERNAME}
            - VULSCANO_CISCO_ROUTER_PASSWORD=${VULSCANO_CISCO_ROUTER_PASSWORD}
            - VULSCANO_DOCKER_VOLUME_NAME=${VULSCANO_DOCKER_VOLUME_NAME}
            - VULSCANO_DOCKER_JOVAL_IMAGE=${VULSCANO_DOCKER_JOVAL_IMAGE}
            - DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}
            - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}
            - DOCKER_HUB_EMAIL=${DOCKER_HUB_EMAIL}
            - VULSCANO_DB_USERNAME=${VULSCANO_DB_USERNAME}
            - VULSCANO_DB_PASSWORD=${VULSCANO_DB_PASSWORD}
            - ANUTA_NCX_HOST=${ANUTA_NCX_HOST}
            - ANUTA_NCX_BASE64_AUTH=${ANUTA_NCX_BASE64_AUTH}
       volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - vulscanovol:/opt/vulscano/data

       network_mode: host
     #   ports:
     #        - "${VULSCANO_HTTPS_PORT}:8443"
     #   networks:
     #        - vulscano-net

    # Vulscano Postgres DB
    vulscano-db:
       image: tatacomm/vulscanodb:beta
       restart: always
       hostname: vulscano-db
       stdin_open: true
       tty: true
       privileged: true
       environment:
            - POSTGRES_DB=vulscanodb
            - POSTGRES_USER=${VULSCANO_DB_USERNAME}
            - POSTGRES_PASSWORD=${VULSCANO_DB_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/vulscanodata

       network_mode: host
     #   ports:
     #        - "5432:5432"
     #   networks:
     #        - vulscano-net
       volumes:
            - postgres_db_data_vol:/var/lib/postgresql/data/vulscanodata
            - postgres_db_conf_vol:/etc/postgresql/conf

     # Vulscano PgAdmin
    vulscano-db-admin:
       image: dpage/pgadmin4
       restart: always
       hostname: vulscano-db-admin
       environment:
            - PGADMIN_DEFAULT_EMAIL=root@vulscano.com
            - PGADMIN_DEFAULT_PASSWORD=vulscano
            - PGADMIN_ENABLE_TLS=True
       ports:
            - "8443:443"
       networks:
            - vulscano-net
       volumes:
            - "${VULSCANO_BASE_PATH}/pgadmin/vulscano-dbadmin.cer:/certs/server.cert"
            - "${VULSCANO_BASE_PATH}/pgadmin/vulscano-dbadmin.key:/certs/server.key"

networks:
   vulscano-net:
       driver: bridge
volumes:
  vulscanovol:
       external: true
  postgres_db_data_vol:
       external: true
  postgres_db_conf_vol:
       external: true
...