---
version: "3.7"

services:
    # Vulscano API Core
    vulscano-core:
       image: tatacomm/vulscano:beta
       restart: always
       stdin_open: true
       tty: true
       hostname: vulscano-core
       depends_on:
            - vulscano-db
       environment:
            - VULSCANO_HTTPS_PORT=${VULSCANO_HTTPS_PORT}
            - VULSCANO_OPENVULN_CLIENT_ID=${VULSCANO_OPENVULN_CLIENT_ID}
            - VULSCANO_OPENVULN_CLIENT_SECRET=${VULSCANO_OPENVULN_CLIENT_SECRET}
            - VULSCANO_DOCKER_VOLUME_NAME=${VULSCANO_DOCKER_VOLUME_NAME}
            - VSCAN_AGENT_HOST=${VSCAN_AGENT_HOST}
            - VSCAN_AGENT_PORT=${VSCAN_AGENT_PORT}
            - VULSCANO_DB_USERNAME=${VULSCANO_DB_USERNAME}
            - VULSCANO_DB_PASSWORD=${VULSCANO_DB_PASSWORD}
            - VULSCANO_DB_DATABASE_NAME=${VULSCANO_DB_DATABASE_NAME}
            - VULSCANO_DB_HOST=${VULSCANO_DB_HOST}
            - ANUTA_NCX_HOST=${ANUTA_NCX_HOST}
            - ANUTA_NCX_BASE64_AUTH=${ANUTA_NCX_BASE64_AUTH}
            - VSCAN_REDIS_HOST=${VSCAN_REDIS_HOST}
            - VSCAN_REDIS_PASSWORD=${VSCAN_REDIS_PASSWORD}
            - VSCAN_SECRET_KEY=${VSCAN_SECRET_KEY}
     #   volumes:
     #        - vulscanovol:/opt/vulscano/data

       network_mode: host
    

    # Vulscano Postgres DB
    vulscano-db:
       image: tatacomm/vulscanodb:beta
       restart: always
       hostname: vulscano-db
       stdin_open: true
       tty: true
       privileged: true
       environment:
            - POSTGRES_DB=vulscanodb
            - POSTGRES_USER=${VULSCANO_DB_USERNAME}
            - POSTGRES_PASSWORD=${VULSCANO_DB_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/vulscanodata

       network_mode: host
    
       volumes:
            - postgres_db_data_vol:/var/lib/postgresql/data/vulscanodata
            - postgres_db_conf_vol:/etc/postgresql/conf

     # Vulscano PgAdmin
    vulscano-db-admin:
       image: dpage/pgadmin4
       restart: always
       hostname: vulscano-db-admin
       environment:
            - PGADMIN_DEFAULT_EMAIL=root@vulscano.com
            - PGADMIN_DEFAULT_PASSWORD=vulscano
            - PGADMIN_ENABLE_TLS=True
       ports:
            - "8443:443"
       networks:
            - vulscano-net
       volumes:
            - "${VULSCANO_BASE_PATH}/pgadmin/vulscano-dbadmin.cer:/certs/server.cert"
            - "${VULSCANO_BASE_PATH}/pgadmin/vulscano-dbadmin.key:/certs/server.key"

     # VSCAN Redis Cache
    vscan-cache:
       image: tatacomm/vscan-cache:beta
       restart: always
       hostname: vscan-cache
       ports:
            - "6379:6379"
       networks:
            - vulscano-net
     
     # VSCAN Agent
    vscan-agent:
       image: tatacomm/vscan-agent:beta
       restart: always
       hostname: vscan-agent
       ports:
            - "${VSCAN_AGENT_BIND_PORT}:${VSCAN_AGENT_BIND_PORT}"
       environment:
            - VSCAN_AGENT_BIND_PORT=50051
            - JAVA_TOOL_OPTIONS="-XX:+UnlockExperimentalVMOptions -Xms2g -Xmx2g -XX:+UseZGC -XX:+UseNUMA -XX:+UseLargePages"
       networks:
            - vulscano-net

networks:
   vulscano-net:
       driver: bridge
volumes:
#   vulscanovol:
#        external: true
  postgres_db_data_vol:
       external: true
  postgres_db_conf_vol:
       external: true
...