---
version: "3.2"

services:
    # Vulscano API Core
    vulscano-core:
       image: tatacomm/vulscano:latest
       restart: always
       stdin_open: true
       tty: true
       hostname: vulscano-core
       depends_on:
            - vulscano-db
       environment:
            - VULSCANO_OPENVULN_CLIENT_ID=${VULSCANO_OPENVULN_CLIENT_ID}
            - VULSCANO_OPENVULN_CLIENT_SECRET=${VULSCANO_OPENVULN_CLIENT_SECRET}
            - VULSCANO_CISCO_ROUTER_USERNAME=${VULSCANO_CISCO_ROUTER_USERNAME}
            - VULSCANO_CISCO_ROUTER_PASSWORD=${VULSCANO_CISCO_ROUTER_PASSWORD}
            - VULSCANO_DOCKER_VOLUME_NAME=${VULSCANO_DOCKER_VOLUME_NAME}
            - VULSCANO_DOCKER_JOVAL_IMAGE=${VULSCANO_DOCKER_JOVAL_IMAGE}
            - DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}
            - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}
            - DOCKER_HUB_EMAIL=${DOCKER_HUB_EMAIL}
       volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - vulscanovol:/opt/vulscano/data
       ports:
            - "${VULSCANO_HTTPS_PORT}:8443"
       networks:
            - vulscano-net

    # Vulscano Postgres DB
    vulscano-db:
       image: postgres:11-alpine
       restart: always
       hostname: vulscano-db
       environment:
            - POSTGRES_DB=vulscanodb
            - POSTGRES_USER=${VULSCANODB_USERNAME}
            - POSTGRES_PASSWORD=${VULSCANODB_PASSWORD}
       ports:
            - "5432:5432"
       networks:
            - vulscano-net
       volumes:
            - postgresdbvol:/var/lib/postgres/data
networks:
   vulscano-net:
       driver: bridge
volumes:
  vulscanovol:
       external: true
  postgresdbvol:
       external: true
...