apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vscan-controller
  name: vscan-controller
  namespace: vscan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vscan-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vscan-controller
    spec:
      containers:
        - image: tatacomm/vulscano:beta
          imagePullPolicy: Always
          name: vscan-controller
          stdin: true 
          tty: true
          ports:
            - containerPort: 443
          env:
            - name: ANUTA_NCX_BASE64_AUTH
              valueFrom:
                secretKeyRef:
                  name: vscan-secrets
                  key: ANUTA_NCX_BASE64_AUTH
            - name: VSCAN_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vscan-secrets
                  key: VSCAN_REDIS_PASSWORD
            - name: VSCAN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: vscan-secrets
                  key: VSCAN_SECRET_KEY
            - name: VULSCANO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vscan-secrets
                  key: VULSCANO_DB_PASSWORD
            - name: VULSCANO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vscan-secrets
                  key: VULSCANO_DB_USERNAME
            - name: VULSCANO_OPENVULN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: vscan-secrets
                  key: VULSCANO_OPENVULN_CLIENT_ID
            - name: VULSCANO_OPENVULN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vscan-secrets
                  key: VULSCANO_OPENVULN_CLIENT_SECRET
            - name: ANUTA_NCX_HOST
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: ANUTA_NCX_HOST
            - name: VSCAN_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: VSCAN_AGENT_HOST
            - name: VSCAN_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: VSCAN_AGENT_PORT
            - name: VSCAN_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: VSCAN_REDIS_HOST
            - name: VULSCANO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: VULSCANO_DB_HOST
            
            - name: VULSCANO_DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: VULSCANO_DB_DATABASE_NAME
            - name: VULSCANO_HTTPS_PORT
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: VULSCANO_HTTPS_PORT
            - name: VULSCANO_MODE
              valueFrom:
                configMapKeyRef:
                  name: vscan-confmap
                  key: VULSCANO_MODE
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      imagePullSecrets:
        - name: docker-secret
status: {}
