// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-02-06 12:01:26.238563 +0700 +07 m=+0.029947712

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Swagger API documentation for TATA Communications Vulscano.",
        "title": "Vulscano API Documentation",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Vulscano API Support",
            "url": "https://github.com/lucabrasi83/vulscano/issues",
            "email": "sebastien.pouplin@tatacommunications.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "vulscano.vsnl.co.in:443",
    "basePath": "/api/v1",
    "paths": {
        "/ping": {
            "get": {
                "description": "Verify the API is responding to HTTP requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Ping Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handlers.PingAPIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.PingAPIResponse": {
            "type": "object",
            "properties": {
                "golangRuntime": {
                    "type": "string"
                },
                "pong": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
